### ISSUE TITLE
When you click a button in a container, container's on_click event also triggers

### ISSUE THREAD

**Issue by mabazud** [flet-dev/flet#1248] opened 2023-04-04 01:21 UTC
I put some controls in a flet.Container including buttons,
when i click a button, Container's on_click event also triggers.

I am using Container's on_click event to choose the Container,
and button's on click event to do something else.

Container's on click event triggers before the button's event,
so i can not avoid the issue

This issue does not happen all the time, but happens frequently

**Comment by gbrandt** [comment] 2023-04-04 03:23
duplicate of https://github.com/flet-dev/flet/issues/1154 ?

**Comment by mabazud** [comment] 2023-04-04 20:41
Sorry i have missed it,
And thank you for your reply

**Closed** 2023-04-05 03:18 UTC
