### ISSUE TITLE
Cann't get local json file for Lottie on Windows

### ISSUE THREAD

**Issue by pwd491** [flet-dev/flet#3364] opened 2024-05-27 10:46 UTC
**Description**
Cann't get local file from assets folder on WIndows.

**Code example to reproduce the issue:**

```python
import flet as ft

def main(page: ft.Page):
    lottie = ft.Lottie("a.json")
    image = ft.Image("a.jpg")

    page.add(lottie, image)
    page.update()

ft.app(main)
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Flet version (`pip show flet`)**:

```
(paste your output here)
```

**Give your `requirements.txt` file (don't `pip freeze`, instead give direct packages):**

```
(The requirements)
```

**Operating system**:

**Additional environment details:**

**Comment by ndonkoHenri** [comment] 2024-05-27 12:28
Closing as duplicate of https://github.com/flet-dev/flet/issues/3082

Please read the comments in that issue.

**Closed by ndonkoHenri** 2024-05-27 12:28 UTC

**Comment by blackCmd** [comment] 2024-11-26 11:16
Works on Ubuntu.
But not work on Windows.
