### ISSUE TITLE
Async and Notifications.

### ISSUE THREAD

**Issue by applicatlat** [flet-dev/flet#2847] opened 2024-03-10 17:57 UTC
Hi. I used plyer in my code to push notifications when the time comes. And used async functions throughout my project hoping that that would make my code work in android. I develop on Windows 11 and it was working fine on it. When I used it on my android phone it did not work. Because I could not debug while using it I do not know what the problem is but the program did not work. What happens is that the app starts, when it is time to send notifications it closes itself. The notifications also work on windows. I put the plyer on my requirements text. So here is my suggestion. Can you please put a guideline how to make ann android app works in background and make flet to send notification via the app? To make it clear I am not using a server to push it but within from the app.

**Comment by ndonkoHenri** [comment] 2024-03-15 06:33
Closing as duplicate of https://github.com/flet-dev/flet/issues/516

**Closed** 2024-03-15 06:34 UTC
Labels: duplicate

**Comment by ndonkoHenri** [comment] 2024-03-15 18:23
The concern is thesame: Notifications 
That's why I marked as duplicate.

You can comment in that issue on what you expect... similar to the others.
