### ISSUE TITLE
"Drag and Drop" type control for dragging files to flutter desktop window

### ISSUE THREAD

**Issue by Zvetkov** [flet-dev/flet#1892] opened 2023-10-01 19:31 UTC
For a familiar desktop UX flet apps are missing ability to work with files dragged on the app window. I would like to request this feature to be added.

**(Optional): Suggest A Solution**

This Flutter package seems to be doing what is requested, but I don't really know if this is a complete solution.
https://pub.dev/packages/desktop_drop

**Comment by leleogere** [comment] 2023-12-08 08:27
This would be very useful! It would be very useful if this callback could be added to any control in general (something like `on_dropped_file`, that would take a `ft.FilePickerResultEvent` as parameter?).

Some examples of useful features that could be achieved with that:
- create a button "Pick file" that allows the user to either click to get the file picker, or simply drop a file on it directly
- create a grid of placeholder elements, and allow the user to fill it with photos directly by dropping the pictures in the location they want in the grid

**Comment by Skquark** [comment] 2024-02-02 12:33
I've also really wanted this feature to be able to drag and drop a file on top of my file picker text fields and put in the path.  I've searched around all the plugins and agree with @Zvetkov that _**desktop_drop**_ is the best and easiest solution for all platforms.  I'd be willing to program this control myself if @FeodorFitsner agrees it's a good core feature that's wanted.  My Flet app has over 50 file picker fields, for uploading images, videos, audio files, and I've been wanting file dropping feature since the beginning, like every other desktop app supports now.
It's just a simple invisible container to wrap around any child content, nothing too fancy needed.  I picture the interface like this:
`FileDrop(content=TextField(.....), on_drag_done=drag_done, on_drag_entered=drag_entered, on_drag_exited=drag_exited, disabled=False)`
Nice and elegant, the callbacks would return a `FilePickerResultEvent` as @leleogere suggested, so we get e.files with `List[FilePickerFile]` and we could get fancy with our UIs if we wanted to shade the container or stack a + file indicator or whatever, even show errors on_drag_entered if it's the wrong file extensions or multiple files when we only want one.. I'm excited about seeing it implemented, any objections or suggestions?

**Comment by leleogere** [comment] 2024-02-02 12:42
This implementation is way smarter and modulable than the simple callback I proposed. Being able to react to entering the area and not only on the actual dropping is very nice!

**Comment by ndonkoHenri** [comment] 2024-08-24 17:16
Closing as duplicate of #112

**Closed** 2024-08-24 17:16 UTC
Labels: duplicate
