### ISSUE TITLE
I'm confused, after page. update(), page==None?

### ISSUE THREAD

**Issue by huangxulei** [flet-dev/flet#2603] opened 2024-02-11 09:04 UTC
`
def init(self):
        self.page.views.clear()
        self.page.views.append(
            View(
                "/",
                [self.appbar, self.layout],
                padding=padding.all(0)
            )
        )
        print('self.page.views', self.page.views)
        self.page.update()
        print(self.page.views)

`

**Comment by huangxulei** [comment] 2024-02-11 09:07
![error](https://github.com/flet-dev/flet/assets/11734379/666ebdbd-676e-49d6-a664-9f43de6a4b75)

**Comment by taaaf11** [comment] 2024-02-11 10:13
For a class, the constructor function should be `__init__` not just `init`.

**Comment by huangxulei** [comment] 2024-02-11 11:57
> For a class, the constructor function should be `__init__` not just `init`. Try this and check if this solves the issue

no ，init is a class ‘s function，not __init__ ’   I just wrote this name as init

**Comment by huangxulei** [comment] 2024-02-11 11:58
> > For a class, the constructor function should be `__init__` not just `init`. Try this and check if this solves the issue
> 
> no ，init is a class ‘s function，not `__init__’` I just wrote this name as init

**Comment by taaaf11** [comment] 2024-02-11 13:20
```python
import flet as ft


def main(page: ft.Page):
    page.views.clear()
    page.views.append(ft.View("/", padding=ft.padding.all(0)))
    print("page.views", page.views)
    page.update()
    print(f"page.views: {page.views}")


ft.app(main)
```

This code is working properly, I can't reproduce the error.

**Comment by huangxulei** [comment] 2024-02-11 13:28
> ```python
> import flet as ft
> 
> 
> def main(page: ft.Page):
>     page.views.clear()
>     page.views.append(ft.View("/", padding=ft.padding.all(0)))
>     print("page.views", page.views)
>     page.update()
>     print(f"page.views: {page.views}")
> 
> 
> ft.app(main)
> ```
> 
> gives
> 
> ```
> page.views [View(route='/')]
> page.views: [View(route='/', padding='{"l":0,"t":0,"r":0,"b":0}')]
> ```
> 
> This code is working properly, I can't reproduce the error.

thank you! I don't know where the problem lies

**Comment by taaaf11** [comment] 2024-02-11 13:34
Can you create a repo with minimal repro code?

**Comment by huangxulei** [comment] 2024-02-11 13:42
https://github.com/EmmetZ/ncm-downloader
I git this code，Maybe you can download and run it to see if it works

**Comment by taaaf11** [comment] 2024-02-11 13:49
In your code, change every `self.page` to `self.page_` in the code

**Comment by huangxulei** [comment] 2024-02-11 13:59
> In your code, change every `self.page` to `self.page_` in the code. This is the solution

What is the difference?  self.page and self.page_  I see many official examples using self. page

**Comment by taaaf11** [comment] 2024-02-11 13:59
> > In your code, change every `self.page` to `self.page_` in the code. This is the solution
> 
> What is the difference? self.page and self.page_ I see many official examples using self. page

Where?? Can you please provide me a link?

**Comment by taaaf11** [comment] 2024-02-11 14:01
I think this is what some controls do set their `page` attribute themeselves. Maybe this is the reason. @FeodorFitsner

**Comment by huangxulei** [comment] 2024-02-11 14:04
> I think this is what some controls do set their `page` attribute themeselves. Maybe this is the reason. @FeodorFitsner

maybe, self.page reset the original

**Comment by taaaf11** [comment] 2024-02-11 14:08
> > I think this is what some controls do set their `page` attribute themeselves. Maybe this is the reason. @FeodorFitsner
> 
> maybe, self.page reset the original

maybe

**Comment by taaaf11** [comment] 2024-02-11 15:01
> thank you very much!

No problem. Now, close the issue

**Closed** 2024-02-11 15:06 UTC
