### ISSUE TITLE
Want to lock orientation of android apps

### ISSUE THREAD

**Issue by imadityacoder** [flet-dev/flet#4286] opened 2024-11-01 10:53 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Recently I create a todo app in flet and convert into apk. After installing apk in my android phone and when my phone rotate, **the GUI also rotate** to look **very bad** for using.

Therefore, I want a property for page to lock orientation in code.
Thanks!

**Comment by yunguangli** [comment] 2024-11-01 11:14
good one. I need this feature too.

**Comment by ndonkoHenri** [comment] 2024-11-01 12:01
Closing this issue as duplicate of #2694

**Closed by ndonkoHenri** 2024-11-01 12:01 UTC
