### ISSUE TITLE
Error when building Windows

### ISSUE THREAD

**Issue by Ambassador-of-programming** [flet-dev/flet#4518] opened 2024-12-07 13:35 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

On the new version pip install flet==0.25.1 there is an error when building via (nuitka --onefile main.py)

here are the dependencies
undetected-chromedriver = “*”
beautifulsoup4 = “*”
pandas = “*”
openpyxl = “*”
numpy = “*”
flet = “*”
nuitka = “==2.4.8”

python_full_version = “3.12.7”

and here is the startup error itself. everything worked fine on older versions.
![Снимок экрана 2024-12-07 110310](https://github.com/user-attachments/assets/e2ad5b12-9660-4ad1-9800-96bec06088b9)

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

nuitka --onefile main.py    

### Screenshots / Videos

<details open>
<summary>Captures</summary>

[Upload media here]

</details>

### Operating System

Windows

### Operating system details

11

### Flet version

 0.25.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Ambassador-of-programming** [comment] 2024-12-07 14:57
I just checked and in version flet = “==0.24.1” everything works fine

**Comment by azhago** [comment] 2024-12-09 11:40
Hi,
It seems to try to download flet on first start and can't retrieve some files.

The files (flet.exe and dlls) had to be present in %userprofile%\.flet\bin\flet-<ver> where <ver> is actually 0.25.1

It tries to download :
https://github.com/flet-dev/flet/releases/download/v0.25.1/flet-windows.zip
but the file does not exist (nor for 0.25) but exists for 0.24.1

Why are we downloading the flet bin on first start, as they are embedded in the exe when packing for windows?

as a workaround till the problem is corrected, @Ambassador-of-programming  you can add that at the beginning of your main.py:
```    import flet_desktop.version
    home = Path().home().joinpath(
            ".flet", "bin", f"flet-{flet_desktop.version.version}"
        )
    if not home.exists():
        bin_dir = Path(__file__).parent / "flet" / "bin"
        for file in bin_dir.rglob("*"):
            if file.is_file():
                dest = home / file.relative_to(bin_dir)
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(file, dest)
            elif file.is_dir():
                dest = home / file.relative_to(bin_dir)
                dest.mkdir(parents=True, exist_ok=True)```

**Comment by Ambassador-of-programming** [comment] 2024-12-10 07:28
> Привет. Похоже, что при первом запуске программа пытается загрузить flet и не может извлечь некоторые файлы.
> 
> Файлы (flet.exe и dll) должны были присутствовать в %userprofile%.flet\bin\flet-, где на самом деле находится 0.25.1
> 
> Он пытается загрузить: https://github.com/flet-dev/flet/releases/download/v0.25.1/flet-windows.zip , но файл не существует (и для 0.25), но существует для 0.24.1
> 
> Почему мы загружаем flet bin при первом запуске, если они встроены в exe-файл при упаковке для Windows?
> 
> как обходной путь, пока проблема не будет устранена,@Ambassador-of-programming Вы можете добавить это в начало вашего main.py:
> 
> ```
>     home = Path().home().joinpath(
>             ".flet", "bin", f"flet-{flet_desktop.version.version}"
>         )
>     if not home.exists():
>         bin_dir = Path(__file__).parent / "flet" / "bin"
>         for file in bin_dir.rglob("*"):
>             if file.is_file():
>                 dest = home / file.relative_to(bin_dir)
>                 dest.parent.mkdir(parents=True, exist_ok=True)
>                 shutil.copy2(file, dest)
>             elif file.is_dir():
>                 dest = home / file.relative_to(bin_dir)
>                 dest.mkdir(parents=True, exist_ok=True)
> ```
> 
> Он скопирует запрошенные файлы туда, где это необходимо, и приложение запустится.



> Hi, It seems to try to download flet on first start and can't retrieve some files.
> 
> The files (flet.exe and dlls) had to be present in %userprofile%.flet\bin\flet- where is actually 0.25.1
> 
> It tries to download : https://github.com/flet-dev/flet/releases/download/v0.25.1/flet-windows.zip but the file does not exist (nor for 0.25) but exists for 0.24.1
> 
> Why are we downloading the flet bin on first start, as they are embedded in the exe when packing for windows?
> 
> as a workaround till the problem is corrected, @Ambassador-of-programming you can add that at the beginning of your main.py:
> 
> ```
>     home = Path().home().joinpath(
>             ".flet", "bin", f"flet-{flet_desktop.version.version}"
>         )
>     if not home.exists():
>         bin_dir = Path(__file__).parent / "flet" / "bin"
>         for file in bin_dir.rglob("*"):
>             if file.is_file():
>                 dest = home / file.relative_to(bin_dir)
>                 dest.parent.mkdir(parents=True, exist_ok=True)
>                 shutil.copy2(file, dest)
>             elif file.is_dir():
>                 dest = home / file.relative_to(bin_dir)
>                 dest.mkdir(parents=True, exist_ok=True)
> ```
> 
> It will copy the requested files where needed and app will run.

Hopefully it will be fixed soon.

**Comment by Ambassador-of-programming** [comment] 2024-12-11 06:40
> I have been facing same. but now everything working fine. 'flet/releases/download/v0.25.1/flet-windows.zip' has been updated. just extract to user/.flet. or flet will do itself.

I'll have to try and test it. I work freelance as a developer and I care about stability for my clients

**Comment by FeodorFitsner** [comment] 2024-12-12 18:59
It should be fixed now. Closing this one.
Also, there is another related issue: https://github.com/flet-dev/flet/issues/4549

**Closed by FeodorFitsner** 2024-12-12 18:59 UTC
Labels: bug, packaging, platform: windows
