### ISSUE TITLE
ERROR:websocket:timed out - goodbye WARNING:websocket:websocket connected

### ISSUE THREAD

**Issue by monkeycc** [flet-dev/flet#343] opened 2022-09-17 12:14 UTC
```
ERROR:websocket:timed out - goodbye 
WARNING:websocket:websocket connected
```

Whether this prompt is normal

Can I not prompt

**Comment by FeodorFitsner** [comment] 2022-09-17 18:33
Duplicate of https://github.com/flet-dev/flet/issues/321

**Closed by FeodorFitsner** 2022-09-17 18:33 UTC
