### ISSUE TITLE
Testing integrated flutter package

### ISSUE THREAD

**Issue by Dave-d-1st** [flet-dev/flet#4048] opened 2024-09-24 23:09 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

When trying to integrate an existing flutter package into flet, I found out that it wasn't possible to test it by running flet run and you have to build the package before the effect takes place

**Comment by ndonkoHenri** [comment] 2024-09-25 11:26
Duplicate of https://github.com/flet-dev/flet/issues/3878

**Closed** 2024-09-25 11:26 UTC
Labels: duplicate
