### ISSUE TITLE
Bug: Text width property and bgcolor property untuned

### ISSUE THREAD

**Issue by burhansvural** [flet-dev/flet#2030] opened 2023-11-04 16:46 UTC
**Description**

When you assign a value to the text width property and then assign a background color, only the area equal to the width of the text is painted. Normally, an area equal to the assigned width value should be painted.

**Code example to reproduce the issue:**
textAlan3=ft.Text("103",width=300,size=55,text_align=ft.TextAlign.END,color="#021c66",bgcolor=ft.colors.AMBER_300,weight=ft.FontWeight.BOLD)

**Describe the results you received:**

![Ekran görüntüsü 2023-11-04 194444](https://github.com/flet-dev/flet/assets/149883930/75d2c442-89e2-452f-8afc-7c16176752df)

**Flet version (`pip show flet`)**:
0.11.0

**Operating system**:
Windows 11 pro

**Comment by ndonkoHenri** [comment] 2023-11-04 18:29
Sorry, but I don't seem to understand your issue. 
Can you please better explain?

**Comment by burhansvural** [comment] 2023-11-04 19:06
TheEthicalBoy ***@***.***>, 4 Kas 2023 Cmt, 21:29 tarihinde
şunu yazdı:

**Comment by burhansvural** [comment] 2023-11-04 19:18
example code:

import flet as ft

def main(page:ft.Page):
    page.window_width=600
    page.window_height=600



    page.title="Using Text Widget"

    page.scroll=ft.ScrollMode.AUTO

    page.theme_mode=ft.ThemeMode.LIGHT
    page.vertical_alignment=ft.MainAxisAlignment.CENTER
    page.horizontal_alignment=ft.CrossAxisAlignment.CENTER

    #don't using width
    textField1=ft.Text("103",size=55,text_align=ft.TextAlign.START,color=
"#021c66",bgcolor=ft.colors.AMBER_300,weight=ft.FontWeight.BOLD)
    textField2=ft.Text("103",width=page.window_width,size=42,text_align=ft.
TextAlign.START,color="#021c66",bgcolor=ft.colors.AMBER_300,weight=ft.
FontWeight.BOLD)



    page.add(
        textField1,
        textField2
             )

    page.update()

ft.app(target=main,assets_dir="assets")

Burhan Süleyman Vural ***@***.***>, 4 Kas 2023 Cmt, 22:05
tarihinde şunu yazdı:

**Comment by burhansvural** [comment] 2023-11-04 19:58
![flet_bug_text_widget](https://github.com/flet-dev/flet/assets/149883930/9550c49e-bf63-47a0-b662-b91fb52df28e)

**Comment by ndonkoHenri** [comment] 2023-11-05 00:27
That's an interesting concern. I don't know if the issue is located on flet's end, or on flutter's.
Nevertheless, below is a suggestion (while waiting a word from the maintainers):

```py
import flet as ft


def main(page: ft.Page):
    page.add(
        ft.Container(
            content=ft.Text(
                "103",
                # width=300,
                size=55,
                text_align=ft.TextAlign.END,
                color="#021c66",
                # bgcolor=ft.colors.AMBER_300,
                weight=ft.FontWeight.BOLD,
            ),
            width=300,
            bgcolor=ft.colors.AMBER_300,
            alignment=ft.alignment.center_left  # left align the text as in your image
        )
    )


ft.app(main)
```

**Comment by burhansvural** [comment] 2023-11-05 09:26
As in this example, there is a mismatch between the controls

TheEthicalBoy ***@***.***>, 5 Kas 2023 Paz, 03:27 tarihinde
şunu yazdı:

**Comment by ndonkoHenri** [comment] 2023-11-05 15:28
What do you mean by mismatch?

**Comment by ndonkoHenri** [comment] 2024-05-29 00:54
The Flutter `Text` widget itself has no `width` property. However, to increase it's width, Flet makes use of the `ConstrainedBox` widget which is wrapped over the `Text`.
The thing is, when you use this `ConstrainedBox` to give a widget more width, the widget itself doesn't necessarily expand to fill this new width.

I suggest you go with the above code i shared, at least, for now. 
If you someday find how to fix this in Flutter, then please share it here - for now I am closing the issue.

**Closed by ndonkoHenri** 2024-05-29 00:54 UTC
