### ISSUE TITLE
Native sharing UI in Flet

### ISSUE THREAD

**Issue by jiho-m0521** [flet-dev/flet#4235] opened 2024-10-26 03:25 UTC
### Duplicate Check

- [x] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

# Native sharing UI, I meant this
![system-level-share-target-9be61b07242ad](https://github.com/user-attachments/assets/4012df0c-3ee0-4fbb-a5f1-f57cd5e962da)

Hello Flet developers who work hard all the time. I would like to suggest a feature to add in flet.

Why is there no feature about sharing something in Flet? This is a Feature that many developers, especially mobile app developers frequently use. For now, to share something, developers need to get the API from each apps. But some of the apps doesn't even have the api. 

I bet this feature is needed not only me but also many mobile app developers using flet.

Best regards.

### Additional details

Links to look for:
[https://pub.dev/packages/share_plus](https://pub.dev/packages/share_plus)

**Comment by Muddassir-Farooq-official** [comment] 2024-10-26 05:19
also need this feature

**Comment by ndonkoHenri** [comment] 2024-10-26 11:06
Closing as duplicate of #2501

**Closed by ndonkoHenri** 2024-10-26 11:06 UTC
Labels: duplicate
