### ISSUE TITLE
No Option For Sending Local Notifications

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3550] opened 2024-06-26 17:10 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

In flet there is still no option available for displaying local notifications and if we open app setting then notifications option is showing disabled we even can't enable it manually I use player module in my code then after build apk when notifications method called app crashes 

### To reproduce

I want to produce local notifications using player 

### Operating System

Windows

### Operating system details

Android

### Flet version

0.23.1

### Regression

No, it isn't

### Suggestions

Kindly give option for local notifications

**Comment by ndonkoHenri** [comment] 2024-06-26 18:13
Closing as duplicate of https://github.com/flet-dev/flet/issues/516

**Closed by ndonkoHenri** 2024-06-26 18:13 UTC
Labels: duplicate
