### ISSUE TITLE
Error MSB8029 and MSB3073 when doing `flet build windows`

### ISSUE THREAD

**Issue by Azka79** [flet-dev/flet#3107] opened 2024-04-27 04:28 UTC
I get a problem every time I do a `flet build windows`. I've tried upgrading my Flutter and Visual Studio. I even tried changing my TEMP file, but the error warnings MSB8029 and MSB3073 kept appearing. What should I do?

here is the error log:
```
Flutter bootstrap directory: D:\TEMP\flet_flutter_build_RwfXu2c21J
Additional Flutter dependencies:
{}
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...
Run subprocess: ['C:\\Users\\nadiy\\dev\\flutter\\bin\\dart.BAT', 'run', 'flutter_launcher_icons']
Resolving dependencies in `D:\TEMP\flet_flutter_build_RwfXu2c21J`... (2.8s)
Downloading packages...
Got dependencies in `D:\TEMP\flet_flutter_build_RwfXu2c21J`.
Building package executable... (1.8s)
Built flutter_launcher_icons:flutter_launcher_icons.
  ════════════════════════════════════════════
     FLUTTER LAUNCHER ICONS (v0.13.1)
  ════════════════════════════════════════════

• Creating default icons Android
• Overwriting the default Android launcher icon with a new icon
• Overwriting default iOS launcher icon with new icon
Creating Icons for Web...
Creating Icons for Windows...
Creating Icons for MacOS...

✓ Successfully generated launcher icons
OK
Packaging Python app...
Run subprocess: ['C:\\Users\\nadiy\\dev\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package',  
'D:\\KULIAH\\SEMESTER 6\\ASN\\Try GUI', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed',    
'--exclude', 'build']
Resolving dependencies in `D:\TEMP\flet_flutter_build_RwfXu2c21J`... 
Downloading packages...
Got dependencies in `D:\TEMP\flet_flutter_build_RwfXu2c21J`.
Building package executable... 
Built serious_python:main.
Running package command
Creating asset directory: D:\TEMP\flet_flutter_build_RwfXu2c21J\app
Copying Python app from D:\KULIAH\SEMESTER 6\ASN\Try GUI to D:\TEMP\serious_python_temp1ff4e45
Installing dependencies [flet-embed] with pip command to D:\TEMP\serious_python_temp1ff4e45\__pypackages__
Extracting Python distributive from D:\TEMP\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to D:\TEMP\hostpython3.11_117fc14c
Compiling Python sources at D:\TEMP\serious_python_temp1ff4e45
Delete unnecessary files with extensions: [.py, .c, .h, .typed, .exe]
Delete unnecessary files and directories: [__pycache__, bin]
Creating app archive at D:\TEMP\flet_flutter_build_RwfXu2c21J\app/app.zip from D:\TEMP\serious_python_temp1ff4e45
Deleting temp directory D:\TEMP\serious_python_temp1ff4e45
Deleting Python directory D:\TEMP\hostpython3.11_117fc14c
OK
Building Windows app...
Run subprocess: ['C:\\Users\\nadiy\\dev\\flutter\\bin\\flutter.BAT', 'build', 'windows']
Resolving dependencies... 
Downloading packages...
  file_picker 6.2.1 (8.0.2 available)
  fl_chart 0.65.0 (0.67.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_markdown 0.6.23 (0.7.1 available)
  flutter_native_splash 2.3.7 (2.4.0 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.4 (10.0.5 available)
  leak_tracker_flutter_testing 3.0.3 (3.0.5 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.12.0 (1.14.0 available)
  package_info_plus 4.2.0 (8.0.0 available)
  package_info_plus_platform_interface 2.0.1 (3.0.0 available)
  petitparser 5.4.0 (6.0.2 available)
  sensors_plus 4.0.2 (5.0.1 available)
  test_api 0.7.0 (0.7.1 available)
  toml 0.14.0 (0.15.0 available)
  xml 6.3.0 (6.5.0 available)
Got dependencies!
18 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\ZERO_CHECK.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\serious_python_windows\CopyPythonDLLs.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\flutter\flutter_wrapper_app.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\flutter\flutter_wrapper_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\screen_retriever\screen_retriever_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\serious_python_windows\serious_python_windows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\include\format(42): warning STL4038: The contents of <format> are available only with C++20 or later. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\serious_python_windows\serious_python_windows_plugin.vcxproj]       
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\url_launcher_windows\url_launcher_windows_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\window_manager\window_manager_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\plugins\window_to_front\window_to_front_plugin.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\runner\try_gui.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\ALL_BUILD.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: The command "setlocal [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmEnd [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmErrorLevel [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: exit /b %1 [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :cmDone [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :VCEnd" exited with code 1. [D:\TEMP\flet_flutter_build_RwfXu2c21J\build\windows\x64\INSTALL.vcxproj]
Building Windows application...                                   156.9s
Build process failed.
Deleting Flutter bootstrap directory D:\TEMP\flet_flutter_build_RwfXu2c21J

Run subprocess: ['C:\\Users\\nadiy\\dev\\flutter\\bin\\flutter.BAT', '--version']
Error building Flet app - see the log of failed command above.
```

The information from my `flutter doctor` does not show any errors and the version of flet is 0.22.0
```
C:\Users\nadiy>flutter doctor -v
[√] Flutter (Channel beta, 3.22.0-0.3.pre, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
    • Flutter version 3.22.0-0.3.pre on channel beta at C:\Users\nadiy\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 87b652410d (3 days ago), 2024-04-23 21:41:18 -0500
    • Engine revision b4bfd45986
    • Dart version 3.4.0 (build 3.4.0-282.3.beta)
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\nadiy\AppData\Local\Android\Sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_SDK_ROOT = C:\Users\nadiy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Build Tools 2022 17.9.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
    • Visual Studio Build Tools 2022 version 17.9.34728.123
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)

[√] VS Code (version 1.88.1)
    • VS Code at C:\Users\nadiy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.86.0

[√] Connected device (4 available)
    • Preview (desktop) • preview • windows-x64    • preview
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3447]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 122.0.6261.131
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 124.0.2478.51

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by EmberLightVFX** [comment] 2024-04-27 23:17
I'm having the exact same problem like you have
I'm running Python 3.12.2
My flet program lies in a /src/ subdir (/src/main.py)

I'm attaching the logs I'm getting when I run `flet build windows src\ -vv`

[log.txt](https://github.com/flet-dev/flet/files/15140266/log.txt)

**Comment by echidne** [comment] 2024-05-13 19:14
Hi.
I had the same prob recently. 
It was working  in the past but I decided to install a "full" version of Visual studio not only the components. Bu I forget to check the case for the installation of the  desktop development tools in c++ and .net. When I installed them again and I stop to have the MSB8029 and MSB3073 errors

**Comment by Azka79** [comment] 2024-05-14 16:52
Thank you for your suggestion. I have tried installing the C++ and .NET development tools as you recommended, but I am still encountering the same errors (MSB8029 and MSB3073).

Could you provide a more detailed explanation on how to check if the C++ and .NET development tools are installed correctly? Is it necessary to install a previous version of MSVC? Perhaps there are specific steps or settings that I might have missed?

**Comment by daxel123** [comment] 2024-05-14 16:59
I had the same problem and I thought it was the reason for my app to crash after compilation, but in my case, I ignore it and my app works. A small advice, try to create a new environment and check the requirements.txt again and run, I miss one package and that was the error.

**Comment by echidne** [comment] 2024-05-14 18:19
@Azka79  do you have only one Visual Build tools installed? Check also if C++ and . net development are installed using modify in the Visual Studio Installer and look if they are checked in "Desktop and Mobile" .
![image](https://github.com/flet-dev/flet/assets/65033881/0535b21a-ed80-4289-a398-abc917ab5d8c)

**Comment by Azka79** [comment] 2024-05-16 01:07
> I had the same problem and I thought it was the reason for my app to crash after compilation, but in my case, I ignore it and my app works. A small advice, try to create a new environment and check the requirements.txt again and run, I miss one package and that was the error.

Is there a way to ignore these errors? In my case, the build folder always gets deleted when the build fails. I don't believe there's an issue with my requirements.txt file. I've successfully published it on the web, but these errors keep appearing when I try to 'build web'.

**Comment by Azka79** [comment] 2024-05-16 01:26
@echidne I believe I already have the necessary C++ and .NET.
![Screenshot 2024-05-16 082526](https://github.com/flet-dev/flet/assets/94118399/87cdc08c-1849-445a-ba12-d7903910a6b6)

**Comment by echidne** [comment] 2024-05-16 08:55
Hi @Azka79 ,
in your screen shot the components look to be correctly installed.
Do you have only one visual studio installed? In my case the prob come because I had several version installed and the one that was using flet did not have the C++ and .Net for desktop installed
![image](https://github.com/flet-dev/flet/assets/65033881/95b07a9b-9013-4ee8-8de5-847ec67bb828)

Other thing to try : to get rid of problem with requirements:
-` flet create helloworld`
- main.py should be:
```
import flet as ft


def main(page: ft.Page):
    page.add(ft.SafeArea(ft.Text("Hello, Flet!")))


ft.app(main)
```
- Check in requirements.txt you have flet
- then` flet build windows`

If that works that means the visual studio components are correctly installed

**Comment by Azka79** [comment] 2024-06-01 11:19
Hi @echidne , 
I'm really sorry for the delayed response to your suggestions. I truly appreciate your patience and am grateful for your valuable input. I only have one version, could this cause problems?
I also tried your suggestion to build on the `flet create myapp` . But I still get the same error
![image](https://github.com/flet-dev/flet/assets/94118399/ecd79a02-16d7-46ec-b29e-58b8b87a906d)

**Comment by Azka79** [comment] 2024-06-01 11:20
Hi @echidne ,
I'm really sorry for the delayed response to your suggestions. I only have one version, could this cause problems?
I also tried your suggestion to build on the flet create myapp . But I still get the same error
![image](https://github.com/flet-dev/flet/assets/94118399/da3b5081-6bbd-4771-bf8d-470c427b98fd)

**Comment by echidne** [comment] 2024-06-01 13:09
Hi @Azka79,
If the simple "hello world" app is not building that means we can exclude problemes with external packages. The most logical explannation I'm able to think about is something is wrong with your VS components installation.
Can you install that [tool from Microsoft](https://github.com/microsoft/vssetup.powershell) ? To do that type that in your Powershell Terminal : 
```
Install-Module VSSetup -Scope CurrentUser
```
Choose the 'Y' option to install it.

then
```
Get-VSSetupInstance
```
and show us the result

**Comment by ReconFito** [comment] 2024-06-01 22:16
Hi,
I have the same error a few minutes ago, the solution it work for me was creating a **requirements.txt** on top of my application folder, inside that file I add **flet==0.22**.

*Sorry for my bad english.*

**Comment by Azka79** [comment] 2024-06-02 04:14
@echidne , i got this error when running `Get-VSSetupInstance`

Get-VSSetupInstance : The 'Get-VSSetupInstance' command was found in the module 'VSSetup', but the module could not be
loaded. For more information, run 'Import-Module VSSetup'.
At line:1 char:1
+ Get-VSSetupInstance
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-VSSetupInstance:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

**Comment by Azka79** [comment] 2024-06-02 04:23
@echidne , I got this 

InstanceId          : 8caa50c6
DisplayName         : Visual Studio Build Tools 2022
InstallationVersion : 17.9.34728.123
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
InstallDate         : 4/8/2024 6:50:33 PM

**Comment by Azka79** [comment] 2024-06-02 04:27
> Hi, I have the same error a few minutes ago, the solution it work for me was creating a **requirements.txt** on top of my application folder, inside that file I add **flet==0.22.***
> 
> _Sorry for my bad english._

I think I've done that when I run flet create myapp, the requrement.txt file automatically contains flet == 0.22.*

**Comment by nanakura** [comment] 2024-06-07 09:56
> Hi @Azka79 ,
> 
> What I did today :
> 
> * I Installed a Windows virtual machine to be sure to start from a fresh environment
> * I installed the Visual Studio with components as stated in the [medium article](https://medium.com/@teamcode20233/a-guide-to-install-desktop-development-with-c-workload-542bb92cfe90) cited in the [Flet documentations  to create Windows apps](https://flet.dev/docs/publish/windows) and choosing the c++ and .net workloads to develop desktop apps (the same ones you picked)
> * I enabled the Developer mode of windows and allow the scripts to be executed in powershell
> * I installed Python 3.12 from python.org and PyCharm(to have an IDE) each time choosing the option that they are Path added
> * I installed the Flutter SDK as described on [their website ](https://docs.flutter.dev/get-started/install/windows/desktop?tab=download)
> * In a virtual environment, I pip install flet
> * then I create the helloworld app and build it  .... without problems !!
> * I installed the Microsoft tool to check the Visual studio installation and I obtained:
>   ![image](https://private-user-images.githubusercontent.com/65033881/336141529-4fae06af-bfc0-4d69-9e38-2d50c45592e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTM4NjQsIm5iZiI6MTcxNzc1MzU2NCwicGF0aCI6Ii82NTAzMzg4MS8zMzYxNDE1MjktNGZhZTA2YWYtYmZjMC00ZDY5LTllMzgtMmQ1MGM0NTU5MmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5NDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMWJlYjU2NDc5ZWJmMmQ0OGU1YWViOWNiMmFlNTA4ZGIzNjk5YmNhOTZjZWM3MjdjYWE1MGRmYjVlMzU4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZ4YigSc_CgAUakEHM0w4U8hPL_H2G9OJSJMexfKcYk)
>   So i compare to your result and I noticed that there is a difference: **you have only the build tools installed when I have the community edition**.
>   I have the feeling your problem could come from that. Perhaps you could try to install teh Visual Studio community editions with the c++ and .net workloads for destop development and see if that fix your bugs?

what is your Windows 10 SDK version, i got the same issue with flet build

**Comment by nanakura** [comment] 2024-06-07 12:15
i can build a flutter project through the following command
```
flutter create test 
cd test 
flutter build windows
```
![image](https://github.com/flet-dev/flet/assets/69560752/07625ed4-3bc5-43cd-b5d3-d219ca7778bc)
is there a build flag to specify a build target directory for flet?

**Comment by echidne** [comment] 2024-06-07 13:49
@nanakura yes you can build from outside the app directory as : 
```
flet build windows path_to_app
```
you can also specify where you want the build to be done as : 
```
flet build windows -o OUTPUT_DIR
```

**Comment by nanakura** [comment] 2024-06-08 02:30
> @nanakura yes you can build from outside the app directory as :
> 
> ```
> flet build windows path_to_app
> ```
> 
> you can also specify where you want the build to be done as :
> 
> ```
> flet build windows -o OUTPUT_DIR
> ```

`-o` flag does not work in my computer, and i find some log 
![image](https://github.com/flet-dev/flet/assets/69560752/8c7fdcbc-0afb-488b-b0dc-f9823c29889f)
It looks like the build error is caused by cmake not finding `vcruntime140_1.dll`, but I can find this file on the disk
![image](https://github.com/flet-dev/flet/assets/69560752/4f2ed5bd-6b73-429d-bcd5-4bc8197fc8fc)

**Comment by echidne** [comment] 2024-06-08 13:18
hi @nanakura ,
What version of visual studio is installed in your system?
Please show a result of the `flutter doctor -v` command  
You say its the -o that causes the error but the error look to happen at building app step not when the build is copyed to the ouput_dir.
Perhaps posting the full log of the building coudl help to know what is happening (you can obtain it in adding the --verbose flag)
I'm not very experimented with Flet but I can try help you.

**Comment by nanakura** [comment] 2024-06-08 14:41
> hi @nanakura , What version of visual studio is installed in your system? Please show a result of the `flutter doctor -v` command You say its the -o that causes the error but the error look to happen at building app step not when the build is copyed to the ouput_dir. Perhaps posting the full log of the building coudl help to know what is happening (you can obtain it in adding the --verbose flag) I'm not very experimented with Flet but I can try help you.

I didn't mean that this error was caused by "-o". Instead, I meant that the build process of flet is performed in the tmp path, and flet deletes the build files after a build failure. I encountered the exact same issue as @Azka79. Here is my `flutter doctor -v`:
```
C:\Users\reika>flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure
you trust this source!
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [版本 10.0.22631.3593],
    locale zh-CN)
    • Flutter version 3.22.1 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (2 weeks ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio 生成工具 2022 17.10.1)
    • Visual Studio at d:\Program Files (x86)\Microsoft Visual
      Studio\2022\BuildTools
    • Visual Studio 生成工具 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for
      detailed instructions).

[√] VS Code (version unknown)
    • VS Code at C:\Users\reika\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    X Unable to determine VS Code version.

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本
      10.0.22631.3593]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome
      124.0.6367.209
    • Edge (web)        • edge    • web-javascript • Microsoft Edge
      125.0.2535.92

```

**Comment by echidne** [comment] 2024-06-08 18:07
hi again @nanakura,
since you said that you could build from a test app and directory but after you said -o flag was not working for you I assumed that the error you shown was raized by the -o flag.
AS I said to @Azka79 the difference I note beetween my working environment and yours is that I'm using Visual Studio Community Edition and not only the components
![image](https://github.com/flet-dev/flet/assets/65033881/b1a635e3-7c91-42c2-97a6-f6afebdea9dc)
I had problems when I was using components but that problemes stopped when i installed the Community edition.

**Comment by nanakura** [comment] 2024-06-09 01:33
> hi again @nanakura, since you said that you could build from a test app and directory but after you said -o flag was not working for you I assumed that the error you shown was raized by the -o flag. AS I said to @Azka79 the difference I note beetween my working environment and yours is that I'm using Visual Studio Community Edition and not only the components ![image](https://private-user-images.githubusercontent.com/65033881/337923655-b1a635e3-7c91-42c2-97a6-f6afebdea9dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4OTY5NjUsIm5iZiI6MTcxNzg5NjY2NSwicGF0aCI6Ii82NTAzMzg4MS8zMzc5MjM2NTUtYjFhNjM1ZTMtN2M5MS00MmMyLTk3YTYtZjZhZmViZGVhOWRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDAxMzEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjc5NzA1YzEzNDRiNTZkNzU4MmUzOTAxNTY2Yzk3ODA0YmRkNzNjODM1YWE4Y2QwZmQzMDg2MDYzOGJlYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2wpoYuae5KmJ_gYgnpnsHUEstnIK61LGMuWumTZ0mnw) I had problems when I was using components but that problemes stopped when i installed the Community edition.

you are right. I installed the Visual Stusio Community Edition and build success
![image](https://github.com/flet-dev/flet/assets/69560752/af356684-9f51-4723-b8e7-ded8f0496a98)

**Comment by Yagniksojitra** [comment] 2024-06-09 14:49
Have installed the Visual Studio and VS Tool only C++ as here in screenshot. 


![Flet](https://github.com/flet-dev/flet/assets/18486071/1e880d62-f38d-41d8-960b-439744145345)

Activate Virtual environment and build the windows app with command "flet build windows" using the Powershell from Visual Studio as shown in screenshot. App build will become successfull.

![image](https://github.com/flet-dev/flet/assets/18486071/88d837a5-13a8-4aa8-89dc-47cab03a1820)

**Comment by Samwellwang** [comment] 2024-07-30 16:48
Hi,
I have the same error a , the solution it work for me was INSTALL Visual Studio community 2022 ， after installed . build successd

**Comment by Azka79** [comment] 2024-08-02 14:46
Sorry for the late response, 
I just tried this suggestion and it worked. The problem is exactly as described, because my visual studio before is not the community edition. Thank you very much for the suggestions given

**Closed** 2024-08-02 14:47 UTC
Labels: packaging, platform: windows

**Comment by MSchwesig** [comment] 2024-08-09 08:11
@Yagniksojitra answer works very well.  Thank you :+1: 

If you don't want to open visiual studio, and just need the build.
You can simply refer to the developer environment in a batch file
I use it like this in a batch file:
```
call "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"
flet build --build-number=1 --build-version="1.0.0"  windows
```
