### ISSUE TITLE
Startup Delay: White Screen Issue and Custom Loading Image Request

### ISSUE THREAD

**Issue by jessic-cmd** [flet-dev/flet#4093] opened 2024-10-04 01:16 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Hello, I used the `flet build windows` command to package the `greeter.py` example from the Flet documentation into a Windows application. However, when I double-click the .exe file to start the program, there is a 3-second white screen before the main interface appears.

I also tried packaging other simple examples, like `hello.py` and `counter.py`, and they all exhibit the same behavior—about 3 seconds of white screen before entering the main interface.

However, when I use the `flet run greeter.py` or `python greeter.py` command to start the program, it immediately enters the main interface without the 3-second white screen.

Is there any way to hide the white screen or replace it with a custom image to inform users that the program is loading?

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft


def main(page: ft.Page):
    page.window.width = 600
    page.window.height = 500
    def btn_click(e):
        if not txt_name.value:
            txt_name.error_text = "Please enter your name"
            page.update()
        else:
            name = txt_name.value
            page.clean()
            page.add(ft.Text(f"Hello, {name}!"))

    txt_name = ft.TextField(label="Your name")


    page.add(txt_name, ft.ElevatedButton("Say hello!", on_click=btn_click))


ft.app(main,view=ft.AppView.FLET_APP_HIDDEN)
```

</details>

### To reproduce

flet build windows

### Expected behavior

I hope the program can immediately display the main interface without showing a white screen, or it can display a custom image indicating that the program is starting and asking the user to wait.

### Screenshots / Videos

<details open>
<summary>Captures</summary>

https://github.com/user-attachments/assets/a7a1ea14-958a-4dc7-91d6-d9daa2be28c9

</details>

### Operating System

Windows

### Operating system details

windows 11 arm-64

### Flet version

0.24.1

### Regression

I'm not sure / I don't know

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by Muddassir-Farooq-official** [comment] 2024-10-04 06:47
It's a common issue in flet

**Comment by ndonkoHenri** [comment] 2024-10-06 14:17
Closing as duplicate of https://github.com/flet-dev/flet/issues/3736

**Closed by ndonkoHenri** 2024-10-06 14:17 UTC
Labels: duplicate

**Comment by Qalxry** [comment] 2025-02-04 16:18
https://flet.dev/docs/reference/types/window/#visible

This can help hide white screen.
