### ISSUE TITLE
Flet Build windows error

### ISSUE THREAD

**Issue by alas82** [flet-dev/flet#2291] opened 2023-12-31 12:35 UTC
i have been trying to build windows app using ( flet build windows ) but i got the following errors 

`
PS C:\Users\Alaa_As\Downloads\pythonapps\myapp> flet build windows
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...OK
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 515, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 701, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Alaa_As\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application
PS C:\Users\Alaa_As\Downloads\pythonapps\myapp> `

please help me to resolve it 
thanks

**Comment by 09u2h4n** [comment] 2023-12-31 16:12
Do you have all dependencies, right? Flutter, android sdk maybe even android studio?

**Comment by FeodorFitsner** [comment] 2023-12-31 19:57
Please run `flet build windows -vv` to get the detailed log and paste it here (with any sensitive data removed of course).

**Comment by alas82** [comment] 2024-01-01 04:38
> Do you have all dependencies, right? Flutter, android sdk maybe even android studio?

yes all of them

**Comment by alas82** [comment] 2024-01-01 04:41
> Please run `flet build windows -vv` to get the detailed log and paste it here (with any sensitive data removed of course).

`PS C:\Users\Al\Downloads\pythonapps\myapp> flet build windows --v
Flutter bootstrap directory: C:\Users\Al\AppData\Local\Temp\flet_flutter_build_LRBzuSZVTe
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying C:\Users\Al\Downloads\pythonapps\myapp\assets\icon.png to C:\Users\Al\AppData\Local\Temp\flet_flutter_build_LRBzuSZVTe\images
OK
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 515, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 701, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by FeodorFitsner** [comment] 2024-01-01 04:45
Should be `-vv`, not `--v`.

**Comment by alas82** [comment] 2024-01-01 06:17
> Should be `-vv`, not `--v`.
 same error 

`PS C:\Users\Al\Downloads\pythonapps\myapp> flet build windows -vv
Flutter bootstrap directory: C:\Users\Al\AppData\Local\Temp\flet_flutter_build_izmzgvgnQn
Creating Flutter bootstrap project...OK
Customizing app icons and splash images...Copying C:\Users\Al\Downloads\pythonapps\myapp\assets\icon.png to C:\Users\Al\AppData\Local\Temp\flet_flutter_build_izmzgvgnQn\images
OK
Generating app icons...Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 515, in handle
    icons_result = self.run(
                   ^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\site-packages\flet\cli\commands\build.py", line 701, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Al\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by david-shu** [comment] 2024-01-02 02:18
The reason for this issue may be as follows: 

shutil. which ('dart ') checks one by one whether ['dart','dart. bat ','dart. com',...] exists and is an executable file,
 but there are both 'dart' and 'dart. bat' files in the Flutter/bin folder, and os.access also determines' dart 'as an executable file. Therefore, shutil. which ('dart') returns the 'dart' file instead of 'dart. bat', which is truly executable.

So, just change the names of the dart and flutter files in the Flutter/bin folder.

**Comment by alas82** [comment] 2024-01-03 18:59
> The reason for this issue may be as follows:
> 
> shutil. which ('dart ') checks one by one whether ['dart','dart. bat ','dart. com',...] exists and is an executable file, but there are both 'dart' and 'dart. bat' files in the Flutter/bin folder, and os.access also determines' dart 'as an executable file. Therefore, shutil. which ('dart') returns the 'dart' file instead of 'dart. bat', which is truly executable.
> 
> So, just change the names of the dart and flutter files in the Flutter/bin folder.

thanks for the hints , it worked but the size of the folder is become 177 mb is all these files are required to distribute for other computers?
regards

**Comment by FeodorFitsner** [comment] 2024-01-08 22:05
Closing as duplicate of https://github.com/flet-dev/flet/issues/2318

Please open another issue re: app size.

**Closed by FeodorFitsner** 2024-01-08 22:05 UTC
