### ISSUE TITLE
Flet Routing Erorr

### ISSUE THREAD

**Issue by saurabhwadekar** [flet-dev/flet#1029] opened 2023-02-12 14:55 UTC
I created home ,about ,contact views and when I tried 
***home > contact > about > contact***
Tried to go through this path then I got error in background.
I have given below code please tell me why this is happening

```python
import flet as ft

def main(page: ft.Page):
    page.title = "Routes Example"

    home_view = ft.View(
                "/",
                [
                    ft.AppBar(title=ft.Text("Flet app"), bgcolor=ft.colors.SURFACE_VARIANT),
                    ft.ElevatedButton("About", on_click=lambda _: page.go("/about")),
                    ft.ElevatedButton("Contact", on_click=lambda _: page.go("/contact")),
                ],
            )

    about_view = ft.View(
                    "/about",
                    [
                        ft.AppBar(title=ft.Text("About"), bgcolor=ft.colors.SURFACE_VARIANT),
                        ft.ElevatedButton("Home", on_click=lambda _: page.go("/")),
                        ft.ElevatedButton("Contact", on_click=lambda _: page.go("/contact")),
                    ],
                )

    contact_view = ft.View(
                    "/contact",
                    [
                        ft.AppBar(title=ft.Text("contact"), bgcolor=ft.colors.SURFACE_VARIANT),
                        ft.ElevatedButton("Home", on_click=lambda _: page.go("/")),
                        ft.ElevatedButton("About", on_click=lambda _: page.go("/about")),
                    ],
                )

    path_list = [
        {"path":"/","clear":True,"view":home_view},
        {"path":"/about","clear":False,"view":about_view},
        {"path":"/contact","clear":False,"view":contact_view},
    ]


    def change_route(route):
        for path in path_list:
            if page.route == path["path"]:
                if path["clear"]:
                    page.views.clear()
                page.views.append(path["view"])
                break

        page.update()

    def view_pop(view):
        page.views.pop()
        top_view = page.views[-1]
        page.go(top_view.route)

    page.on_route_change = change_route
    page.on_view_pop = view_pop
    page.go(page.route)


ft.app(target=main, view=ft.WEB_BROWSER)
```

**Comment by iron3oxide** [comment] 2023-02-12 17:39
Could you show us the error message so we can find the root cause?

 Besides, if you want to save yourself some trouble and code, check out [this library I wrote](https://github.com/iron3oxide/flet-routed-app) for use cases like yours.

**Comment by saurabhwadekar** [comment] 2023-02-13 04:40
I don't see any errors on the terminal but I
***Home > Contact > About > Contact***
   I am not able to switch to any view after the path, when I click on the button, the address changes in the browser but the page does not change.
***Try switching different pages once***

**Comment by iron3oxide** [comment] 2023-02-13 04:56
So if I understand you correctly, you can go through that navigation once, but after that nothing happens anymore? 

That would be because you have to create a new View object each time the route changes. The docs don't explicitly state this, but you can see in the example that is given there that this is how it's supposed to be done. 

In your case, you could simply convert home_view, contact_view and about_view to functions that return the corresponding View objects. Your path_list would stay the same, but in change_route you'd do `page.views.append(path["view"]())` instead.

But again, if you want to save yourself some trouble, consider using the library I mentioned, which would do most of this in the background for you.

**Comment by iron3oxide** [comment] 2023-02-13 05:11
No problem. Let me know over there if anything could be improved or doesn't work. Also, let's close this issue as it seems to be resolved

**Closed** 2023-02-13 05:31 UTC
