### ISSUE TITLE
The code architecture require improve

### ISSUE THREAD

**Issue by calvinweb** [flet-dev/flet#529] opened 2022-10-28 12:40 UTC
Rencently, i road the code of this project, but I found there are several things can be  done in a more beautiful way
  ~~Firstly, `fletd` will be download by the code when the first time run. however,pipy can distribute the packages for each system and architecture, so the you needn't download it by your self, just bundle them into the package, (see flet.py,line 284)~~
 Secondly, the flet client has the same problem  to  the fletd and it will be decompression everytime that system boot on linux, because `/tmp` is a "ramdisk" on most linux. so, just put the uncompression client files into the package this will make it start faster
In addition could you add a full api reference?
(Sorry for my English)

**Comment by calvinweb** [comment] 2022-10-28 13:08
> `fletd` or `flet` is already bundled with the packaged [`flet*.whl`](https://files.pythonhosted.org/packages/5f/b2/7bbd07acc8229fc2a71e14d4b9ee0f00287e4963164d190ab2e630701a57/flet-0.1.63-py3-none-win_amd64.whl) file.
> 
> https://github.com/flet-dev/flet/blob/5f915d5ee60493b192ab7c9f49453e6fea93af5b/sdk/python/flet/flet.py#L275-L286
> 
> https://github.com/flet-dev/flet/blob/5f915d5ee60493b192ab7c9f49453e6fea93af5b/sdk/python/flet/flet.py#L372-L379
> 
> ![image](https://user-images.githubusercontent.com/2276718/198594558-60d26a89-73ec-432e-97ff-72a73399ea04.png)

oh,I forgot to check this, i will make a strikethrough for it, however,the second still require a fix.

**Comment by FeodorFitsner** [comment] 2022-10-28 18:02
That's all related to https://github.com/flet-dev/flet/issues/161

First, it's not a good solution to unpack Flet client to a temp folder. Will be fixed in the next release.
Second, the decision to keep Flet client's `.tar.gz` inside `.zip` was made because ZIP archives do not preserve original file attributes such as "executable". However, I'll explore if it's feasible to do `chmod` instead of unpacking.

**Comment by FeodorFitsner** [comment] 2022-10-28 18:13
Maybe I'm not right regarding attributes inside zip. I'm verifying that.

**Comment by FeodorFitsner** [comment] 2022-10-28 18:13
Anyway, let's close this issue in favour of #161

**Closed by FeodorFitsner** 2022-10-28 18:13 UTC

**Comment by FeodorFitsner** [comment] 2022-10-28 20:07
No, I was wrong! The problem is not permissions, but symlinks. macOS application bundle (Flet.app) has symlinked directories/files inside and `.zip` does not support symlinks, but `.tar.gz` does.

**Comment by calvinweb** [comment] 2022-10-29 02:16
> No, I was wrong! The problem is not permissions, but symlinks. macOS application bundle (Flet.app) has symlinked directories/files inside and `.zip` does not support symlinks, but `.tar.gz` does.

but why but a bundle inside package？i think but the file directly will be better

**Comment by FeodorFitsner** [comment] 2022-10-29 03:09
What do you mean by "file"?

**Comment by calvinweb** [comment] 2022-10-29 03:17
> What do you mean by "file"?

the flet client

**Comment by FeodorFitsner** [comment] 2022-10-29 16:54
On macOS Flutter produces a bundle, not a single executable.
