### ISSUE TITLE
"Unknown control: clipboard" on Android.

### ISSUE THREAD

**Issue by AyberkAtalay0** [flet-dev/flet#2900] opened 2024-03-17 16:41 UTC
**Description:**
I converted a code I copied from the website into an .apk file using the "flet build apk" command and transferred it to my phone. When I run the application, I see the error mentioned below. I can run the application on desktop.

**Requirements:**
```
flet==0.21.1
```

**Operating systems:**
Process on Windows 11, test on Android 13

**Code:**
```python
import flet as ft

async def main(page: ft.Page):
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER
    page.appbar = ft.AppBar(title=ft.Text("Audio Recorder"), center_title=True)

    path = "test-audio-file.wav"

    async def handle_start_recording(e):
        print(f"StartRecording: {path}")
        await audio_rec.start_recording_async(path)

    async def handle_stop_recording(e):
        output_path = await audio_rec.stop_recording_async()
        print(f"StopRecording: {output_path}")
        if page.web and output_path is not None:
            await page.launch_url_async(output_path)

    async def handle_list_devices(e):
        devices = await audio_rec.get_input_devices_async()
        print(devices)

    async def handle_has_permission(e):
        try:
            print(f"HasPermission: {await audio_rec.has_permission_async()}")
        except Exception as e:
            print(e)

    async def handle_pause(e):
        print(f"isRecording: {await audio_rec.is_recording_async()}")
        if await audio_rec.is_recording_async():
            await audio_rec.pause_recording_async()

    async def handle_resume(e):
        print(f"isPaused: {await audio_rec.is_paused_async()}")
        if await audio_rec.is_paused_async():
            await audio_rec.resume_recording_async()

    async def handle_audio_encoding_test(e):
        for i in list(ft.AudioEncoder):
            print(f"{i}: {await audio_rec.is_supported_encoder_async(i)}")

    async def handle_state_change(e):
        print(f"State Changed: {e.data}")

    audio_rec = ft.AudioRecorder(
        audio_encoder=ft.AudioEncoder.WAV,
        on_state_changed=handle_state_change,
    )
    page.overlay.append(audio_rec)
    await page.update_async()

    await page.add_async(
        ft.ElevatedButton("Start Audio Recorder", on_click=handle_start_recording),
        ft.ElevatedButton("Stop Audio Recorder", on_click=handle_stop_recording),
        ft.ElevatedButton("List Devices", on_click=handle_list_devices),
        ft.ElevatedButton("Pause Recording", on_click=handle_pause),
        ft.ElevatedButton("Resume Recording", on_click=handle_resume),
        ft.ElevatedButton("Test AudioEncodings", on_click=handle_audio_encoding_test),
        ft.ElevatedButton("Has Permission", on_click=handle_has_permission),
    )


ft.app(target=main)
```

**Results:**
```
"Unknown control: clipboard"
```
![error1](https://github.com/flet-dev/flet/assets/105879357/443871b3-c317-4283-8121-fca925deb811)

**Comment by ndonkoHenri** [comment] 2024-03-17 21:08
Does this happen with a simple application too (Hello World) ? Or just the above specific code..?

**Comment by AyberkAtalay0** [comment] 2024-03-18 05:05
> Does this happen with a simple application too (Hello World) ? Or just with the above specific code..?

No, "Hello world" is working just fine.

**Comment by AyberkAtalay0** [comment] 2024-03-18 15:11
> Does this happen with a simple application too (Hello World) ? Or just with the above specific code..?

I'm so sorry, I remembered wrong. All applications give the same error with the "flet build apk" command.

**Comment by zLEDT** [comment] 2024-03-22 03:49
Da el mismo error con un simple hello world

**Comment by marwanazd** [comment] 2024-03-25 01:49
use `ft.SafeArea()` on `page.add(ft.SafeArea(content=ft.Column(([,,,,,,]))`

**Comment by AyberkAtalay0** [comment] 2024-03-28 05:24
> use `ft.SafeArea()` on `page.add(ft.SafeArea(content=ft.Column(([,,,,,,]))`

Not working.

**Comment by ndonkoHenri** [comment] 2024-03-28 07:52
I cannot reproduce this issue.
In my video, you can see that the apk works as expected: https://www.youtube.com/watch?v=IcT_QrLWi10

**Comment by Jingyu-yummyFuture** [comment] 2024-05-24 18:48
I meet the same error when I run the command in macOS, switching the device to a linux environment fixed the issue, not sure whether this can help you!

**Comment by ndonkoHenri** [comment] 2024-05-25 12:37
I marked this issue as bug, though i dont know where it might originate.
Can you guys please also share the flet version with which you test?

**Comment by Jingyu-yummyFuture** [comment] 2024-05-27 15:24
I was using flet version 0.19.0 and how I launch the app is by 
`ft.app(name="", target=main, view=None, port=8509, host="0.0.0.0")`
I built and launched the app in a MacOS device then opened it as a web app from an Android device, and it showed the "Unknown control: clipboard" staff
However it worked well under Linux

**Comment by ndonkoHenri** [comment] 2024-09-08 01:13
Closing this issue in favor of https://github.com/flet-dev/flet/issues/3867

Please mention any further details in there.

**Closed by ndonkoHenri** 2024-09-08 01:13 UTC
Labels: bug, packaging, platform: android
