### ISSUE TITLE
IconButton tooltip display problem

### ISSUE THREAD

**Issue by azhago** [flet-dev/flet#3928] opened 2024-09-03 09:46 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

Tooltip for IconButton don't work as expected

With a string as tooltip, displayed tooltip is sourrounded by double quotes
With ft.Tooltip as tooltip, displayed tooltip is like "{"message": xxx}"

### Code sample

<details open><summary>Code</summary>

```python
import flet as ft

def main(page: ft.Page=None) -> None:
    new_tooltip = ft.IconButton(icon=ft.icons.ADD, icon_size=32, tooltip=ft.Tooltip(message="test new tooltip "))
    old_tooltip = ft.IconButton(icon=ft.icons.ADD, icon_size=32, tooltip="test message")

    page.add(new_tooltip)
    page.add(old_tooltip)


if __name__ == "__main__":
    ft.app(target=main)
```

</details>

### To reproduce

simply run above code and over the iconbuttons

### Expected behavior

for string tooltip : not surrounded by doublequotes
for ft.Tooltip : display only the content of message value

### Screenshots / Videos

<details open>
<summary>Captures</summary>
with ft.tooltip:
![image](https://github.com/user-attachments/assets/0d2e3379-9c15-4ee3-bebd-62cad5d83baf)
with string tooltip:
![image](https://github.com/user-attachments/assets/6ce744bc-8df2-4a0b-a66e-c196d466916b)

</details>

### Operating System

Windows

### Operating system details

w11

### Flet version

0.24.0

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

### Additional details

string tooltip were not surrounded by doublequotes on flet 0.22

**Comment by ndonkoHenri** [comment] 2024-09-03 09:53
Duplicate of https://github.com/flet-dev/flet/issues/3920

**Closed** 2024-09-03 09:54 UTC
Labels: duplicate
