### ISSUE TITLE
Add native camera access for Android

### ISSUE THREAD

**Issue by deviagomendes** [flet-dev/flet#3492] opened 2024-06-19 14:56 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Please implement the ability to access the device's native camera on Android directly within the Flet framework. This feature should allow users to open the camera, take pictures, and possibly record videos without needing to use external packages or plugins.

### Suggest a solution

Please implement the ability to access the device's native camera on Android directly within the Flet framework. This feature should allow users to open the camera, take pictures, and possibly record videos without needing to use external packages or plugins.

Suggest a solution:
The preferred solution is to integrate a native camera widget that can be easily added to any Flet application. This widget should provide:

Camera Preview: A live preview of what the camera is seeing.
Capture Button: A button to capture photos.
Video Recording: An optional feature to record videos.
Configuration Options: Ability to set camera resolution, switch between front and back cameras, and adjust focus/zoom settings.
Technical Implementation Details:

Utilize the Flutter camera package (camera) as a base for this feature.
Ensure the implementation is well-integrated with the existing Flet framework, allowing seamless use within Flet applications.
Provide clear documentation and examples demonstrating how to use the camera widget in Flet apps.
Tradeoffs:

Increased complexity in maintaining platform-specific code.
Possible delays in updates due to the need to synchronize with changes in the Flutter camera package.
Future Considerations:

Expansion to support other platforms (iOS, web) for a consistent cross-platform experience.
Integration with other media-related functionalities such as gallery access and media storage.

### Additional details

The ability to access the native camera is a critical feature for many applications, especially those involving media capture, social interactions, and documentation. By adding this feature, Flet will be significantly more useful for developers building rich, interactive applications. Given the high demand and essential nature of this feature, we request that it be prioritized accordingly.

**Comment by ndonkoHenri** [comment] 2024-10-06 02:07
Closing as duplicate of https://github.com/flet-dev/flet/issues/1281

**Closed by ndonkoHenri** 2024-10-06 02:07 UTC
