### ISSUE TITLE
pack command should not delete "dist" folder if specified another with "--distpath"

### ISSUE THREAD

**Issue by IagoBeuller** [flet-dev/flet#2473] opened 2024-01-24 06:48 UTC
I specify the a folder named "pack" to save the executable with --distpath, and instead of deleting "pack" folder, it is deleting "dist", where was deleted lots of important files. Luckly The folder is from google drive, and I could recover the files.

**Comment by taaaf11** [comment] 2024-01-29 02:43
We are working on the issue.

**Comment by taaaf11** [comment] 2024-01-29 02:44
@FeodorFitsner I have created #2500 pull request to solve the issue... Kindly review the pr

**Comment by taaaf11** [comment] 2024-02-03 02:43
@IagoBeuller The issue is now resolved. Kindly close the issue. Install pre-release (obviously in a virtual environment) or wait for the next release ;)

**Closed** 2024-02-03 08:54 UTC
