### ISSUE TITLE
Radio and checkbox color

### ISSUE THREAD

**Issue by vv2006-mc** [flet-dev/flet#390] opened 2022-09-25 15:21 UTC
I created an application with a custom color scheme. I could change all the colors except the Radio's and the checkbox's colors. I would prefer to change those colors to suit my color scheme.

### **light theme**
![image](https://user-images.githubusercontent.com/62519221/192151746-c7796f75-434f-4384-b2b9-e9cb3e4c0aaa.png)
![image](https://user-images.githubusercontent.com/62519221/192151704-a3a8fc00-b4cc-420f-a053-779598ac7857.png)

### **dark theme,**
![wg5WhHpTpx](https://user-images.githubusercontent.com/62519221/192151607-9b90bb64-714b-4560-8594-760631f448e6.png)
![image](https://user-images.githubusercontent.com/62519221/192151669-292c0f3e-bcf7-4386-a391-25b807e28cc6.png)

is there a way to add this feature?

**Comment by vv2006-mc** [comment] 2022-09-25 15:24
![PR5iBl38o0](https://user-images.githubusercontent.com/62519221/192151378-f64ff8d4-7e59-4667-847d-18bcbf3f3cd1.png)
![JC7PA54obq](https://user-images.githubusercontent.com/62519221/192151455-e24a981f-c1da-497e-a324-514fecdc44c6.png)

**Comment by FeodorFitsner** [comment] 2022-09-25 16:19
Closing as a duplicate of https://github.com/flet-dev/flet/issues/320

**Closed by FeodorFitsner** 2022-09-25 16:19 UTC
