### ISSUE TITLE
Flet App Not Publishing On Play Store

### ISSUE THREAD

**Issue by Muddassir-Farooq-official** [flet-dev/flet#4001] opened 2024-09-16 20:07 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

i am unable to publish flet android bundle on Google Play Store made with flet build aab and facing issue You uploaded an APK or Android App Bundle that was signed in debug mode. You need to sign your APK or Android App Bundle in release mode

### Code sample

<details open><summary>Code</summary>

```python
[Paste your code here]
```

</details>

### To reproduce

want to publish apps on playstore with ease

### Screenshots / Videos

<details open>
<summary>Captures</summary>

![image](https://github.com/user-attachments/assets/b441395c-dc91-4362-afdd-4c21d610380f)

</details>

### Operating System

macOS

### Operating system details

Windows 10

### Flet version

0.24.1

### Regression

No, it isn't

### Suggestions

make this method simpler to publish aps on Paly Store

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment] 2024-09-16 22:44
Closing as duplicate of https://github.com/flet-dev/flet/issues/2868

**Closed** 2024-09-16 22:45 UTC
Labels: duplicate
