### ISSUE TITLE
Push notifications with user input 

### ISSUE THREAD

**Issue by SebastianSosa** [flet-dev/flet#3274] opened 2024-05-11 09:09 UTC
Hi,

If possible for the mobile application (or desktop too), it would be great to have push notifications. Even better would be the possibility to receive user input in text fields or any other form of user input widgets.

Thank you for considering it.

**Comment by ndonkoHenri** [comment] 2024-05-11 17:08
Duplicate of https://github.com/flet-dev/flet/issues/516

**Closed** 2024-05-11 17:09 UTC
Labels: duplicate

**Comment by Ayberk-Irmak** [comment] 2025-04-06 21:36
Hey everyone! 👋

I finally found a solution for sending notifications in Flet mobile applications using Pyjnius!
Since I know that many of you have been struggling with this issue, I decided to make a video tutorial explaining the entire process.
Check it out, and let me know what you think!

🔗 Video Link: [How to Send Notifications in Flet using Pyjnius](https://www.youtube.com/watch?v=kXWKaylIhCg)

Hope it helps! 😊
