### ISSUE TITLE
flet build apk 

### ISSUE THREAD

**Issue by ssseee66** [flet-dev/flet#4567] opened 2024-12-14 10:05 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

These days, the use of p4a to package flet applications into apk suddenly appeared an error, has always been the use of p4a packaging is very stable, but now the packaging environment has not been modified but can not be packaged, flet version 0.24.1

### Code sample

/home/feiyuan/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:257:
error: cannot find symbol
[        ]         if (registrar != null) {
[        ]             ^
[        ]   symbol:   variable registrar
[        ]   location: class FilePickerPlugin
[        ]
/home/feiyuan/.pub-cache/hosted/pub.dev/file_picker-8.1.5/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java:260:
error: cannot find symbol
[        ]             registrar.addActivityResultListener(this.delegate);
[        ]             ^
[        ]   symbol:   variable registrar
[        ]   location: class FilePickerPlugin
[        ] 2 errors

### To reproduce

flet build apk -vv

### Screenshots / Videos

![Snipaste_2024-12-14_17-47-22](https://github.com/user-attachments/assets/142febda-f8ac-4551-aba6-752bab3a375d)

### Operating System

Linux

### Operating system details

Ubuntu 18.04（WSL）

### Flet version

0.24.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Suggestions

I need to package the flet application as an apk

### Logs

<details open><summary>Logs</summary>

```console
[Paste your logs here]
```

</details>

**Comment by ndonkoHenri** [comment] 2024-12-14 13:20
Closing as duplicate of https://github.com/flet-dev/flet/issues/4564

**Closed** 2024-12-14 13:20 UTC
Labels: duplicate
