### ISSUE TITLE
`flet build` includes full `flet` package instead of `flet-embed` if some project dependency depends on `flet` 

### ISSUE THREAD

**Issue by mottibz** [flet-dev/flet#3114] opened 2024-04-28 09:45 UTC
Hello,

Following filing this in the Discord Help forum, I remembered that I should have filed it here :-)

I have built today a Windows executable with no problem (the PyInstaller way).
I have built an apk in the past with no problem.
I tried to build an apk today and it got stucked in the middle. I copied the few last lines of the process below.
Python version: 3.11.6
Flet version: 0.21.1
Flutter version: 3.19.3
Build command line: flet build apk --verbose

LAST FEW LINES OF OUTPUT:
Packaging Python app...
Run subprocess: ['C:\\src\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package', 'C:\\Flet\\MyHome',
'--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude',
'build']
Building package executable...
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\motti\AppData\Local\Temp\flet_flutter_build_pFgJYXKyDC\app
Copying Python app from C:\Flet\MyHome to C:\Users\motti\AppData\Local\Temp\serious_python_temp620d94dd
Configured mobile platform with sitecustomize.py at C:\Users\motti\AppData\Local\Temp\serious_python_sitecustomize73b6c7b4\sitecustomize.py
Installing dependencies [paho-mqtt, requests, flet_timer, flet-embed] with pip command to C:\Users\motti\AppData\Local\Temp\serious_python_temp620d94dd\__pypackages__
Extracting Python distributive from C:\Users\motti\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\motti\AppData\Local\Temp\hostpython3.11_ec512379

I also tried upgrading Flet and Flutter.
Flet version: 0.22.0
Flutter version: 3.19.6 (the doctor printed at the end of the upgrade that all is OK)

GOT A SIMILAR SITUATION:
Packaging Python app...
Run subprocess: ['C:\\src\\flutter\\bin\\dart.BAT', 'run', 'serious_python:main', 'package', 'C:\\Flet\\MyHome',
'--mobile', '--platform', 'mobile', '--dep-mappings', 'flet=flet-embed', '--req-deps', 'flet-embed', '--exclude',
'build']
Building package executable...
Built serious_python:main.
Running package command
Creating asset directory: C:\Users\motti\AppData\Local\Temp\flet_flutter_build_RB8FJAbZbp\app
Copying Python app from C:\Flet\MyHome to C:\Users\motti\AppData\Local\Temp\serious_python_temp96338385
Configured mobile platform with sitecustomize.py at C:\Users\motti\AppData\Local\Temp\serious_python_sitecustomize53b371c3\sitecustomize.py
Installing dependencies [paho-mqtt, requests, flet_timer, flet-embed] with pip command to C:\Users\motti\AppData\Local\Temp\serious_python_temp96338385\__pypackages__
Extracting Python distributive from C:\Users\motti\AppData\Local\Temp\cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz to C:\Users\motti\AppData\Local\Temp\hostpython3.11_d3456a60

Any help will be highly appreciated!!!
Thanks a lot!!!

**Comment by mottibz** [comment] 2024-04-28 09:50
Some more info:

As the process got stuck, I did a Control-C and was asked to type Y. See below the screen output:

^CTerminate batch job (Y/N)? y
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python-3-11-6\Scripts\flet.exe\__main__.py", line 7, in <module>
  File "C:\Python-3-11-6\Lib\site-packages\flet\cli\cli.py", line 83, in main
    args.handler(args)
  File "C:\Python-3-11-6\Lib\site-packages\flet\cli\commands\build.py", line 679, in handle
    package_result = self.run(
                     ^^^^^^^^^
  File "C:\Python-3-11-6\Lib\site-packages\flet\cli\commands\build.py", line 828, in run
    r = subprocess.run(
        ^^^^^^^^^^^^^^^
  File "C:\Python-3-11-6\Lib\subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python-3-11-6\Lib\subprocess.py", line 1201, in communicate
    self.wait()
  File "C:\Python-3-11-6\Lib\subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python-3-11-6\Lib\subprocess.py", line 1588, in _wait
    result = _winapi.WaitForSingleObject(self._handle,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
^CTerminate batch job (Y/N)? y

C:\Flet\MyHome>

**Comment by vishnu-rvb** [comment] 2024-04-29 03:27
i too have the same problem , i require only a single external package numpy alone and this causing compilation issue

**Comment by FeodorFitsner** [comment] 2024-04-30 18:23
Try running with `flet build apk -vv`?

**Comment by mottibz** [comment] 2024-04-30 19:21
Hi Feodor,
I run using "flet build apk -vv".
It passed the previous point but got stuck later with an error and I did not get back the C prompt. Some of the line before the error are below. Please let me know... Thanks!

Obtaining dependency information for pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 from https://files.pythonhosted.org/packages/ed/76/9a17032880ed27f2dbd490c77a3431cbc80f47ba81534131de3c2846e736/pydantic-2.7.1-py3-none-any.whl.metadata
VERBOSE: Using cached pydantic-2.7.1-py3-none-any.whl.metadata (107 kB)
VERBOSE: Collecting typing-extensions>=4.8.0 (from fastapi<1,>=0->flet->flet_timer)
VERBOSE: Obtaining dependency information for typing-extensions>=4.8.0 from https://files.pythonhosted.org/packages/01/f3/936e209267d6ef7510322191003885de524fc48d1b43269810cd589ceaf5/typing_extensions-4.11.0-py3-none-any.whl.metadata
VERBOSE: Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
VERBOSE: Collecting anyio (from httpx<1,>=0->flet-runtime==0.22.0->flet-embed)
VERBOSE: Obtaining dependency information for anyio from https://files.pythonhosted.org/packages/14/fd/2f20c40b45e4fb4324834aea24bd4afdf1143390242c0b33774da0e2e34f/anyio-4.3.0-py3-none-any.whl.metadata
VERBOSE: Using cached anyio-4.3.0-py3-none-any.whl.metadata (4.6 kB)
VERBOSE: Collecting httpcore==1.* (from httpx<1,>=0->flet-runtime==0.22.0->flet-embed)
VERBOSE: Obtaining dependency information for httpcore==1.* from https://files.pythonhosted.org/packages/78/d4/e5d7e4f2174f8a4d63c8897d79eb8fe2503f7ecc03282fee1fa2719c2704/httpcore-1.0.5-py3-none-any.whl.metadata
VERBOSE: Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
VERBOSE: Collecting sniffio (from httpx<1,>=0->flet-runtime==0.22.0->flet-embed)
VERBOSE: Obtaining dependency information for sniffio from https://files.pythonhosted.org/packages/e9/44/75a9c9421471a6c4805dbf2356f7c181a29c1879239abab1ea2cc8f38b40/sniffio-1.3.1-py3-none-any.whl.metadata
VERBOSE: Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
VERBOSE: Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0->flet-runtime==0.22.0->flet-embed)
VERBOSE: Obtaining dependency information for h11<0.15,>=0.13 from https://files.pythonhosted.org/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl.metadata
VERBOSE: Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
VERBOSE: Collecting pypng (from qrcode<8.0.0,>=7.4.2->flet->flet_timer)
VERBOSE: Obtaining dependency information for pypng from https://files.pythonhosted.org/packages/3e/b9/3766cc361d93edb2ce81e2e1f87dd98f314d7d513877a342d31b30741680/pypng-0.20220715.0-py3-none-any.whl.metadata
VERBOSE: Using cached pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
VERBOSE: Collecting colorama>=0.4 (from uvicorn[standard]<1,>=0->flet->flet_timer)
VERBOSE: Obtaining dependency information for colorama>=0.4 from https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl.metadata
VERBOSE: Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
VERBOSE: Collecting httptools>=0.5.0 (from uvicorn[standard]<1,>=0->flet->flet_timer)
VERBOSE: Using cached httptools-0.6.1.tar.gz (191 kB)
VERBOSE: Installing build dependencies: started
VERBOSE: Installing build dependencies: finished with status 'done'
VERBOSE: Getting requirements to build wheel: started
VERBOSE: Getting requirements to build wheel: finished with status 'done'
VERBOSE: Preparing metadata (pyproject.toml): started
VERBOSE: Preparing metadata (pyproject.toml): finished with status 'done'
VERBOSE: Collecting python-dotenv>=0.13 (from uvicorn[standard]<1,>=0->flet->flet_timer)
VERBOSE: Obtaining dependency information for python-dotenv>=0.13 from https://files.pythonhosted.org/packages/6a/3e/b68c118422ec867fa7ab88444e1274aa40681c606d59ac27de5a5588f082/python_dotenv-1.0.1-py3-none-any.whl.metadata
VERBOSE: Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
VERBOSE: Collecting watchfiles>=0.13 (from uvicorn[standard]<1,>=0->flet->flet_timer)
VERBOSE: Using cached watchfiles-0.21.0.tar.gz (37 kB)
VERBOSE: Installing build dependencies: started
VERBOSE: Installing build dependencies: finished with status 'error'

**Comment by mottibz** [comment] 2024-04-30 19:27
paho-mqtt
requests
flet_timer

**Comment by FeodorFitsner** [comment] 2024-04-30 19:36
OK, I seem know where the problem is.
Both `paho-mqtt` and `requests` are pure-Python packages and will work on Android as is.
`flet_timer` is a pure-Python package as well, but it depends on `flet` package which should not be used on mobile.
When you have just `flet` in `requirements.txt` Flet build tool replaces `flet` with `flet-embed` (which is a trimmed `flet` library).

I don't have an immediate answer on how to fix that.

**Comment by FeodorFitsner** [comment] 2024-04-30 19:36
If you can just copy `flet_timer` into your project and then list `flet` in `requirements.txt` then it should do the trick.

**Comment by mottibz** [comment] 2024-04-30 19:38
I am a little confused from your description :-)
- When you write "copy flet_timer into you project", you mean to take its code and add it as one more source file in my project?

**Comment by FeodorFitsner** [comment] 2024-04-30 19:41
Exactly! It's just one file under MIT license: https://github.com/panos-stavrianos/flet_timer/blob/master/flet_timer/flet_timer.py

**Comment by mottibz** [comment] 2024-04-30 19:42
I will try tomorrow:
- Move the "flet_timer" source code as one more module in my code
- Change the requirements.txt file in two ways: (1) Remove "flet_timer", (2) Add "flet" as first line
Will update you after I test it.
Thanks a lot for your help!

**Comment by mottibz** [comment] 2024-05-01 13:30
OK, status report :-)
- Did the above steps
- Generated Windows executable (flet pack with pyinstaller). Worked fine
- Generated Android APK. Success with that
- Had a fight with my phone until I was able to install the APK to it
- When I started the app, I got an error. Screen capture attached:

![Screenshot_20240501_161807](https://github.com/flet-dev/flet/assets/11439987/6a682777-eaf6-4a21-8708-9d062ec8020e)

- My read is that flet_timer is importing from interval_timer and it can't find it. Strangely, it worked fine in the Windows executable.
- Is interval_timer clear for inclusion in a flet APK? If so, I will pip install it and add it to requirements.txt.
- Please let me know. Thanks!
-

**Comment by praskuma** [comment] 2024-05-01 14:58
There is something strange I observed.

As long as there is no requirements.txt 
or requiremnets.txt is empty

build works fine

The moment you add a module(let it be any module) to requirements,txt, 
"flet build apk --verbose"
gets stuck at
"Extracting Python distributive from"

**Comment by FeodorFitsner** [comment] 2024-05-01 16:59
So, `flet_timer` depends on `interval-timer`: https://pypi.org/project/interval-timer/

Add `interval-timer` into `requirements.txt` and it should be fine.

**Comment by mottibz** [comment] 2024-05-01 17:12
Instead of all these dependencies and lots of code, I decided to write my own timer routine (7 lines) :-)
I will test it tomorrow within an APK and see if it works...

**Comment by ndonkoHenri** [comment] 2024-08-25 19:30
This issue will be fixed by #3163

**Closed by ndonkoHenri** 2024-08-25 19:30 UTC
Labels: bug, packaging
