### ISSUE TITLE
`Notification` control

### ISSUE THREAD

**Issue by theN1C1** [flet-dev/flet#4393] opened 2024-11-18 15:36 UTC
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the requested feature

Add the ability to send notifications on android, ios, windows, linux.

### Suggest a solution

https://pub.dev/packages/flutter_local_notifications

_A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform._

### Screenshots

![android_notification](https://github.com/user-attachments/assets/f4234951-45ec-49b7-b710-5aca19450920)
![ios_notification](https://github.com/user-attachments/assets/b9edbcd3-269d-4f1e-9f54-11bbc75a689a)

### Additional details

You can also move notifications from the [plyer](https://pypi.org/project/plyer/) lib

**Comment by ndonkoHenri** [comment] 2024-11-18 21:21
Closing as duplicate of https://github.com/flet-dev/flet/issues/516

**Closed** 2024-11-18 21:21 UTC
Labels: duplicate
